services:

  postgres-db:

    image: postgres:latest
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sen@c2023
      POSTGRES_DB: bd_inovacao

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  app:
    build: .
    container_name: app-spring

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/bd_inovacao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sen@c2023

    ports:
      - "8080:8080"

    depends_on:
      - postgres-db


volumes:
  db-data:
    driver: local