spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bd_inovacao
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    secret: "jwt-inovacao"
    expiration_time: 5
